In [1]:
import pickle
import numpy as np
import datetime

In [2]:
data_file_name = 'face_data_w.npz'
test_file_name = 'test_data_w.npz'

names = ['20_man', '40_man', '60_man', '20_woman', '40_woman', '60_woman']

# 1이 옆 2가 위
for name in names:
    with open('./data/w/'+name, 'rb') as f:
        temp = pickle.load(f)
        print(len(temp[0][2]))
        for i in range(len(temp)):
            slt = np.ndarray(shape=(1, 2))
            slt.fill(0)
            slt[0][temp[i][1]] = 1

            alt = np.ndarray(shape=(1, 3))
            alt.fill(0)
            alt[0][temp[i][0]] = 1                
        
            dt = np.asarray(temp[i][2])
            dt = dt.reshape(-1, 80, 55, 1)
            
            if i == 0:
                sex_labels1 = slt
                age_labels1 = alt
                data1 = dt
            else:
                sex_labels1 = np.concatenate((sex_labels1, slt), axis = 0)
                age_labels1 = np.concatenate((age_labels1, alt), axis = 0)
                data1 = np.concatenate((data1, dt), axis = 0)
                
    if name == '20_man':
        sex_labels = sex_labels1
        age_labels = age_labels1
        data = data1
    else:
        sex_labels = np.concatenate((sex_labels, sex_labels1), axis = 0)
        age_labels = np.concatenate((age_labels, age_labels1), axis = 0)
        data = np.concatenate((data, data1), axis = 0)
    
    print(name,",",datetime.datetime.now().time())
print("end")

idx = np.random.permutation(len(data))

idx_tr = idx[0:int(0.8 * len(data))]
idx_te = idx[int(0.8 * len(data)):]

trS = sex_labels[idx_tr, :]
teS = sex_labels[idx_te, :]

trA = age_labels[idx_tr, :]
teA = age_labels[idx_te, :]

tr = data[idx_tr, :]
te = data[idx_te, :]



np.savez(data_file_name, sex_labels = trS, age_labels = trA, data = tr)
np.savez(test_file_name, sex_labels = teS, age_labels = teA, data = te)

4400
20_man , 14:21:36.158069
4400
40_man , 14:21:36.572092
4400
60_man , 14:21:36.689099
4400
20_woman , 14:21:38.892225
4400
40_woman , 14:21:39.098237
4400
60_woman , 14:21:39.189242
end


In [3]:
f = np.load('face_data_w.npz')
l = f['age_labels']
print(l[3:30])

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]
